<a href="https://colab.research.google.com/github/Beerschtein/PyTorch/blob/main/HW_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# !pip3 install torch torchvision

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [1]:
import torch
from IPython import display
import numpy as np
import random

In [2]:
# 1. Создайте случайный FloatTensor размера 3x4x5
a = torch.randn(3, 4, 5)
a

tensor([[[ 2.3131,  0.9252,  0.3832,  1.8600, -0.1040],
         [-0.2052,  0.3623, -0.3293, -0.0560,  0.4311],
         [ 2.2705,  1.0010, -1.1665,  0.7576,  0.0171],
         [-0.3278, -0.1843,  1.3840, -0.8594, -0.7188]],

        [[-0.4351, -0.0600, -0.9068, -2.1411,  1.7967],
         [ 0.2052,  0.7363, -0.4056,  1.4246,  1.9047],
         [ 0.6493,  1.0378,  0.2961, -0.1206, -1.4165],
         [ 1.0136,  0.4381,  0.6249,  1.4204, -0.9215]],

        [[ 0.0097,  1.4935,  0.8897, -0.5492, -0.5181],
         [-1.5922,  1.6315,  0.6646, -0.5642,  1.9105],
         [-0.0306, -0.7260, -1.0251,  0.0617, -0.3630],
         [ 0.4667, -0.1279, -0.9968, -0.9976, -1.6062]]])

In [3]:
# 2. Выведите его форму (shape)
a.size()

torch.Size([3, 4, 5])

In [4]:
print(a.type())

torch.FloatTensor


In [5]:
# 3. Приведите его к форме 6х10
a = a.reshape(6, 10)
a

tensor([[ 2.3131,  0.9252,  0.3832,  1.8600, -0.1040, -0.2052,  0.3623, -0.3293,
         -0.0560,  0.4311],
        [ 2.2705,  1.0010, -1.1665,  0.7576,  0.0171, -0.3278, -0.1843,  1.3840,
         -0.8594, -0.7188],
        [-0.4351, -0.0600, -0.9068, -2.1411,  1.7967,  0.2052,  0.7363, -0.4056,
          1.4246,  1.9047],
        [ 0.6493,  1.0378,  0.2961, -0.1206, -1.4165,  1.0136,  0.4381,  0.6249,
          1.4204, -0.9215],
        [ 0.0097,  1.4935,  0.8897, -0.5492, -0.5181, -1.5922,  1.6315,  0.6646,
         -0.5642,  1.9105],
        [-0.0306, -0.7260, -1.0251,  0.0617, -0.3630,  0.4667, -0.1279, -0.9968,
         -0.9976, -1.6062]])

In [6]:
# 4. Создайте случайный IntTensor размера 10
b = torch.randn(10).type(torch.IntTensor)
b

tensor([ 1,  0, -1,  0,  0, -1,  0, -1,  1, -1], dtype=torch.int32)

In [7]:
print(b.type())

torch.IntTensor


In [8]:
b.shape

torch.Size([10])

In [9]:
# Ещё один случайный IntTensor размера 10, но из заданного множества
c = torch.randint(100, size=(10,)).type(torch.IntTensor)
c

tensor([98, 40, 32, 57, 27, 90, 75, 83, 55, 61], dtype=torch.int32)

In [10]:
print(c.type())

torch.IntTensor


In [11]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно
d = torch.mul(a, b)

In [12]:
print(d)

tensor([[ 2.3131,  0.0000, -0.3832,  0.0000, -0.0000,  0.2052,  0.0000,  0.3293,
         -0.0560, -0.4311],
        [ 2.2705,  0.0000,  1.1665,  0.0000,  0.0000,  0.3278, -0.0000, -1.3840,
         -0.8594,  0.7188],
        [-0.4351, -0.0000,  0.9068, -0.0000,  0.0000, -0.2052,  0.0000,  0.4056,
          1.4246, -1.9047],
        [ 0.6493,  0.0000, -0.2961, -0.0000, -0.0000, -1.0136,  0.0000, -0.6249,
          1.4204,  0.9215],
        [ 0.0097,  0.0000, -0.8897, -0.0000, -0.0000,  1.5922,  0.0000, -0.6646,
         -0.5642, -1.9105],
        [-0.0306, -0.0000,  1.0251,  0.0000, -0.0000, -0.4667, -0.0000,  0.9968,
         -0.9976,  1.6062]])


In [13]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти
x = d.T
x

tensor([[ 2.3131,  2.2705, -0.4351,  0.6493,  0.0097, -0.0306],
        [ 0.0000,  0.0000, -0.0000,  0.0000,  0.0000, -0.0000],
        [-0.3832,  1.1665,  0.9068, -0.2961, -0.8897,  1.0251],
        [ 0.0000,  0.0000, -0.0000, -0.0000, -0.0000,  0.0000],
        [-0.0000,  0.0000,  0.0000, -0.0000, -0.0000, -0.0000],
        [ 0.2052,  0.3278, -0.2052, -1.0136,  1.5922, -0.4667],
        [ 0.0000, -0.0000,  0.0000,  0.0000,  0.0000, -0.0000],
        [ 0.3293, -1.3840,  0.4056, -0.6249, -0.6646,  0.9968],
        [-0.0560, -0.8594,  1.4246,  1.4204, -0.5642, -0.9976],
        [-0.4311,  0.7188, -1.9047,  0.9215, -1.9105,  1.6062]])

In [14]:
d_matr = torch.mm(d, x, out=None)

In [15]:
d_matr

tensor([[ 5.8368,  4.1546, -0.5212,  0.7248,  1.3266, -0.8677],
        [ 4.1546,  9.7940, -3.1521,  1.1032, -0.4625,  1.6058],
        [-0.5212, -3.1521,  6.8755, -0.3281,  1.4277, -3.0375],
        [ 0.7248,  1.1032, -0.3281,  4.7939, -3.4906, -0.4102],
        [ 1.3266, -0.4625,  1.4277, -3.4906,  7.7367, -4.8237],
        [-0.8677,  1.6058, -3.0375, -0.4102, -4.8237,  5.8384]])

In [16]:
d_matr.size()

torch.Size([6, 6])

In [26]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

x = torch.tensor([1.0], requires_grad=True)
z = torch.tensor([0.5], requires_grad=True)
t = torch.tensor([2.0], requires_grad=True)


In [27]:
y = x ** 3 + 1 * z - 75 * t
y.backward(x, z, t)

In [28]:
x.grad

tensor([3.], grad_fn=<CopyBackwards>)

In [29]:
z.grad

tensor([1.], grad_fn=<CopyBackwards>)

In [30]:
t.grad

tensor([-75.], grad_fn=<CopyBackwards>)

In [ ]:
# 8. Создайте единичный тензор размера 5x6
z = torch.randn(5, 6)
z

tensor([[ 1.2974, -0.5696, -0.8840, -0.0413, -1.0470, -0.3920],
        [ 0.5095, -0.0980,  0.0874, -1.2118, -0.4353, -0.2600],
        [-0.3722,  1.1890,  0.6100, -0.5904, -0.0410,  0.2466],
        [ 0.1999, -0.1572, -0.0843,  0.3788, -0.3595,  0.0622],
        [ 1.6800, -1.3026, -1.3412,  0.3889, -1.4305, -1.4083]])

In [ ]:
# 9. Переведите его в формат numpy
z.numpy()

array([[ 1.2974216 , -0.56960297, -0.8839749 , -0.04133503, -1.0470216 ,
        -0.3919515 ],
       [ 0.5095299 , -0.09799053,  0.08742466, -1.2118319 , -0.43530098,
        -0.259996  ],
       [-0.3721625 ,  1.1889815 ,  0.6099601 , -0.590413  , -0.04098548,
         0.24656633],
       [ 0.19986428, -0.1571976 , -0.08433155,  0.3788261 , -0.35950917,
         0.06217149],
       [ 1.6800207 , -1.3025749 , -1.3411934 ,  0.38891506, -1.4305401 ,
        -1.4082584 ]], dtype=float32)